services:
  client:
    restart: unless-stopped
    container_name: protiva-frontend
    image: ghcr.io/future-stack/protiva-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      args:
        - NODE_ENV=production
        - NEXT_TELEMETRY_DISABLED=1
        - NEXT_PUBLIC_API_URL=https://api.kaajbd.com.bd
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=https://api.kaajbd.com.bd
    expose:
      - "3000"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
